### PR TITLE
Reactification, redesign

### PR DESCRIPTION
**Pull request by andykog**
- Rewritten in react.js
- Redesigned
- Saving “enable log”, “enable update” state after refresh

I propose to include this pr in 3.0 version, as it brings breaking change — necessity to render `<DevTool />` react component.

### CODE REVIEW

**Comment by mweststrate** [comment]
This is really awesome! Thanks a lot! Gonna play with it and release it asap!

**Comment by andykog** [comment]
Thank you for a great lib :-)

**Comment by mweststrate** [comment]
Small question, users now have to explicitly instantiate the `DevTools` in their React component tree. Is this a deliberate  choice? I could restore the old 'instantiate-if-imported' behavior. Downside of course is that users have less control on where / when it will appear. What do you think?

**Comment by andykog** [comment]
I think this is a mere detail, but explicit instantiation is less magical and more react-ish. Users have an option to always import DevTool, but to render it only in dev environment, if they don't care about a few lines of redundant code in production. Plus the ability to pass options as props.

**Comment by mweststrate** [comment]
Ok, you convinced me :).

**Comment by mweststrate** [comment]
Just released it as 3.0.0 with some minor tweaks. Thanks a lot!

**Pull request closed without merging**
