### PR TITLE
Remove peerDependencies

### PR DESCRIPTION
**Pull request by Strate**
It is hard to use pre-release versions of mobx & mobx-react with this requirements.
See also https://github.com/npm/npm/issues/8854#issuecomment-217664545

### CODE REVIEW

**Comment by Strate** [comment]
@mweststrate what do you think about it? Can I merge?

**Comment by mweststrate** [comment]
Hmm not entirely sure about this one. It makes sure the minimum versions of the required api's are available. Violating peer deps is only a warning afaik in both npm 2 and 3 if you already provided the dependency yourself in the parent package? (which you should)

**Comment by Strate** [comment]
Unfortunatelly, that warning breaks shrinkwrap - shrinkwrap didn't write if unmet peer dependency.
Yet another one way to fix it - is to publish according version of this package, which includes pre-release version in peerDependency. Which is hard to maintain :(.

**Comment by mweststrate** [comment]
It is definitely annoying to use a pre release with these in place, but I think this is the correct thing to.

For now I just copy the folder contents manually when trying to test a fresh version

**Pull request closed without merging**
