### PR TITLE
Chrome extension

### PR DESCRIPTION
**Pull request by andykog**
https://chrome.google.com/webstore/detail/mobx-developer-tools/pfgnfdagidkfgccljigdamigbcnndkod

The design is inspired by react-devtools, 
here is [rough flowchart](https://github.com/mobxjs/mobx-react-devtools/files/681241/mobx-devtool-flowchart.pdf).

Updated react component with the same API can be found on npm: [mobx-devtools] (https://www.npmjs.com/package/mobx-devtools) (don't confuse with mobx-**react**-devtools)

Not sure about:
* If you are using react `DevTool` component and picking dependency tree via extension panel, is it ok, that graph will be displayed both in panel and on the page? Try [mobx-devtools] (https://www.npmjs.com/package/mobx-devtools) package to see what I'm talking about. 
* Is it the right way to completely synchronize state of all the devtool instances. For example, if you open devtool window-panel when using react `DevTool` component, log array will be stored in 1) hook store 2) window-panel store 3) react DevTool store, this is kind of memory wasting, but provides concistency and persistance between panels reopens

Todo:
- [x] Throttle events to improve performance (like react-devtool does)
- [x] Hide mobx-react-related buttons when only mobx found?
- [x] Test API compatibility

### CODE REVIEW

**Comment by lostpebble** [comment]
Great work! Seems to be working fine for me, links in with my MobX app no problem.

Just this error that seems to be consistent:
undefined_error

A small thing that I've noticed too- when you've made a selection at the top (the different icons for the different tools such as "Log state changes in panel") it doesn't remember my selection on page reload so I always have to go and change it back again.

I've only been making use of "Log state to changes in panel" really. But upon trying to use "Select a component and show its rendering tree" (I can't seem to select anything) and "Visualise component re-renders" nothing seems to happen for me.

**Comment by andykog** [comment]
@lostpebble, thanks, fixed

**Comment by mweststrate** [comment]
@andykog promising stuff! For me somehow the extension started working after a while. First it worked correctly, after a while it started crashing the page, and after a browser restart It stopped working at all :-P. I see the following stack trace:

```

backend.js:1170 Uncaught RangeError: Maximum call stack size exceeded
    at cleanUp (chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/build/backend.js:1170:18)
    at chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/build/backend.js:1181:30
    at Array.forEach (native)
    at chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/build/backend.js:1180:29
    at cleanUp (chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/build/backend.js:1186:7)
    at chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/build/backend.js:1181:30
    at Array.forEach (native)
    at chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/build/backend.js:1180:29
    at cleanUp (chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/build/backend.js:1186:7)
    at chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/build/backend.js:1181:30
```

I was testing this demo: https://github.com/mobxjs/mobx-contacts-list

**Comment by andykog** [comment]
@mweststrate, I'm sure that's because of https://github.com/andykog/mobx-react-devtools/blob/3202aa26b8648cc54859be4236ec2db1c12f0e2f/src/backend/agent.js#L6-L15 , there should be better serialization logic to deal with circular links, keeping constructor name...

**Comment by mweststrate** [comment]
@andykog ah. (comment without knowing any further context) Maybe `mobx.toJS` can help? It deals with circular deps. Although using a normal Map is probably even more efficient

**Comment by andykog** [comment]
@mweststrate mobx.toJS doesn't gets rid of circular links, I need this to JSON.stringify(someObject) and pass it to background page.

**Comment by mweststrate** [comment]
@andykog yeah sorry, it doesn't remove them, just doesn't die on them ;-)

**Comment by andykog** [comment]
Fixed

**Comment by burdeasa** [comment]
This extension looks great to me.  I ran a few quick tests with https://github.com/mobxjs/mobx-contacts-list demo.

My question: do you expect this to work with an Electron app?  I currently install the React dev tools extension using electron-devtools-installer.  I attempted to  do the same with this extension:
```
        const { default: installExtension, REACT_DEVELOPER_TOOLS } = require('electron-devtools-installer')
        installExtension('pfgnfdagidkfgccljigdamigbcnndkod')
             .then((name) => logger.log('info', `AddedExtension: ${name}`))
             .catch((err) => logger.log('error', 'An error occurred installing MobX Dev Tools:', err))
        installExtension(REACT_DEVELOPER_TOOLS)
             .then((name) => logger.log('info', `AddedExtension: ${name}`))
             .catch((err) => logger.log('error', 'An error occurred installing React Dev Tools:', err))

```

I did not see any errors from electron-devtools-installer, but it did not appear to work.  In particular, I see the React tab, but I do not see the MobX tab in chrome developer tools.

**Comment by andykog** [comment]
@burdeasa, I'll try to take take a look later, don't have much experience with electron though. Maybe, some unsupported by electron api is being used.

**Comment by andykog** [comment]
Does somebody know how to debug devtool extensions in electron (e.g. background page)? `electron-inspector` doesn't seems to help here.

**Comment by iotch** [comment]
Great work, @andykog! Will be great to have the ability to open the panel as a Chrome Developer tools _tab_, like 'console', 'network', 'elements', etc. Now, if working on a single monitor, the panel hides each time it loses focus.
Also, will be great to have action's store name printed, if available, so instead of
`Action ‘myAction’ ()` print `Action ‘MyStore.myAction’ ()` or something like that.
Thanks!

**Comment by andykog** [comment]
@iotch, it was there, I've just commented it out for some reason, will be updated in chome webstore in about an hour

**Comment by iotch** [comment]
@andykog, thanks! Got updated version. I'm having an issue - sometimes after page refresh the extension is failing to find mobx - shows "Looking for mobx..." screen no matter of observables updates. Reopening Chrome devtools fixes this. Here is the error from a background page:
`Error in event handler for (unknown): Error: Attempting to use a disconnected port object
    at lOne (chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/build/background.js:95:10)`

**Comment by andykog** [comment]
@iotch, strange, can't reproduce it with my apps...

**Comment by iotch** [comment]
I've deleted and reinstalled the extension and its ok so far. Could it be because of update instead of clean install? Some caches, maybe? I can't figure out too, will report if that happens again.

**Comment by andykog** [comment]
@mweststrate, need your review. This PR adds a lot of overhead for on-page devtools, may probobly lead to versions conflicts because of shared global “Agent” instance, but gives the advantage of single codebase.

**Comment by iotch** [comment]
@andykog unfortunately the error `Attempting to use a disconnected port object at lOne` is still here. It happens when using as chrome devtools panel after several page refreshes (F5). I'm using Chrome 56.0.2924.87 (64-bit)

**Comment by andykog** [comment]
@iotch, don't think `Attempting to use a disconnected port object at lOne` is the actual problem. “React Developer Tools” has the same error happening even more often. Will try to reproduce the problem with forever looking for mobx again. I suspect, your project loads mobx.js script in page's `<head></head>`, is that correct?

**Comment by iotch** [comment]
> I suspect, your project loads mobx.js script in page's <head></head>, is that correct?

My project is built with Webpack 2.1 beta.27 + typescript loader (tsc ver. 2.2), targeted ES5.
Output .js file is just before closing body tag.

If the extension is opened in the separate window (with the button next to address bar), everything works fine.

**Comment by asfernandes** [comment]
When I use this extension and "turn log on", my mobx application (built with webpack + typescript), reports error in this backend.js in this place: `superChange.time = change.time;`

When I was using the devtools without the extension (but at this time my application was different than now) the error was not happening.

Full stack trace:

```
[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Cac0010r#0.render()] Error: [mobx] Invariant failed: Cannot obtain atom from undefined
    at invariant (vendor.bundle.js:5972)
    at fail (vendor.bundle.js:5967)
    at getAtom (vendor.bundle.js:5792)
    at Object.getDebugName (vendor.bundle.js:5814)
    at observableName (chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/build/backend.js:1004)
    at ChangesProcessor.push (chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/build/backend.js:1090)
    at Array.<anonymous> (chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/build/backend.js:296)
    at spyReport (vendor.bundle.js:4678)
    at ComputedValue.trackAndCompute (vendor.bundle.js:4119)
    at ComputedValue.get (vendor.bundle.js:4089)
window.console.error
chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/build/backend.js:1059 Uncaught TypeError: Cannot set property 'time' of undefined
    at ChangesProcessor.push (chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/build/backend.js:1059)
    at Array.<anonymous> (chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/build/backend.js:296)
    at spyReport (vendor.bundle.js:4678)
    at spyReportEnd (vendor.bundle.js:4687)
    at Reaction.track (vendor.bundle.js:4578)
    at Cac0010r.reactiveRender [as render] (vendor.bundle.js:2615)
    at vendor.bundle.js:94041
    at measureLifeCyclePerf (vendor.bundle.js:93320)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (vendor.bundle.js:94040)
    at ReactCompositeComponentWrapper._renderValidatedComponent (vendor.bundle.js:94067)
```

**Comment by danrot** [comment]
Wouldn't it be even better to integrate that into the chrome dev tools, instead of an own extension?

**Comment by andykog** [comment]
@asfernandes, thanks for the report, should be fixed in `alpha-11` (will be in chrome store during the next hour).
@iotch, I still can't reliebly reproduce the issue, but `alpha-11` could fix that.

**Comment by iotch** [comment]
@andykog thanks! I have not faced the issue since update, will report anyway. Some of my actions are getting lost, but this was happening with the devtool component to, so I believe it is not related to the extension.

**Comment by iotch** [comment]
When "vizualize component re-renders" is on, I'm getting `Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node` at `chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/build/backend.js:449:28`

This is not happening with devtool component, extension only.

**Comment by andykog** [comment]
@iotch, hah, thanks, fixed in `alpha-12`

**Comment by cpunion** [comment]
@andykog The problem is still in `alpha-12`, if the component unmount when I enable `Visualize component re-renders` and the rendering report is showing, this problem causes. It is very easy to reproduce, because when I change route by react-router, the component will unmount. The component's size is large, and it handles onMouseEnter/Leave event.

```
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at _default.displayRenderingReport (chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/build/backend.js:449:28)
    at chrome-extension://pfgnfdagidkfgccljigdamigbcnndkod/build/backend.js:308:29
```

image

**Comment by andykog** [comment]
@cpunion, that was another problem :-) fixed in alpha-13

**Comment by cpunion** [comment]
@andykog Thanks for quickly fix, it's very robust now.

**Comment by natew** [comment]
just curious whats the status of this?

tried it out and had a few points of feedback:

- freezing entire tab when heavy logging
- add command+k to clear log
- add log scrollback

etc, but would be nice to see progress so this is merged eventually or at least supported somewhere.

**Comment by andykog** [comment]
@natew, thanks for the feedback, I'll take a look later this week. What is scrollback? Some kind of button “scroll to end”?

**Comment by natew** [comment]
Made this quickly, it could be improved a bit: https://github.com/motion/mobx-formatters

Edit: for me it wouldn't let me scroll up, but perhaps it froze before I could.

**Comment by andykog** [comment]
@natew, I've added hotkeys and fixed most obvious issue with the performance (alpha-14), could you check if it helps in some way?

Planning to do in the next update(s):
* Drop synchronisation between different devtools instances (complicates the code and I don't think it gives much benefit)
* Try to fix the issue when it shows nothing unless reloaded (being disconnected)

**Comment by iotch** [comment]
@andykog seems like devtools tab has disappeared again with the latest version (alpha-17) and Chrome 58.0

**Comment by andykog** [comment]
@iotch, what version of mobx are you using? I think it can be related to [mobx#1043](https://github.com/mobxjs/mobx/issues/1043) Does it work on this page https://react-mobx.realworld.io/ ? Do any errors arise in console on main/[background](chrome-extension://chklaanhfefbnpoihckbnefhakgolnmc/_generated_background_page.html) page?

**Comment by iotch** [comment]
I was using 3.1.11 but after update to 3.1.16 everything works fine. Sorry for false alert.

**Comment by andykog** [comment]
Moved to a separate repository https://github.com/andykog/mobx-devtools

**Pull request closed without merging**
